{ config, pkgs, lib, ... }:

{
  home.username = "garinh";
  home.homeDirectory = "/home/garinh";


  programs.home-manager.enable = true;

  # ── Quickshell: bar + notifications (replaces waybar and swaync) ─────────────
  # Started from the Hyprland autostart with hl.exec_cmd("qs").
  # Notification center from a keybind/script:  qs ipc call notifs toggle
  programs.quickshell.enable = true;

  # Live reload: ~/.config/quickshell points straight at /etc/nixos/quickshell
  # (not a store copy), so saving a .qml file there updates the running bar instantly.
  # No rebuild needed for QML edits.
  #xdg.configFile."quickshell".source =
  #  config.lib.file.mkOutOfStoreSymlink "/etc/nixos/quickshell";

  wayland.windowManager.hyprland = {
    enable = true;
    package = null;        # use programs.hyprland from configuration.nix
    portalPackage = null;  # portal already set in configuration.nix
    configType = "lua";
    settings = lib.mkForce { };
    systemd.enable = true; # your Lua already runs dbus-update-activation-environment
    extraConfig = ''
-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives
-- Fixed: env vars now actually applied via hl.env(); blur config consolidated into one block

---@module 'hl'

-- Catppuccin palette (written to ~/.config/hypr/themes/catppuccin.lua by catppuccin/nix)
local colors = require('themes.catppuccin')

hl.monitor({
    output   = "DP-1", -- for laptops generally eDP-0 or eDP-1, and desktops usually DP-1.
    mode     = "1920x1080@240",
    position = "0x0",
    scale    = 1,
})

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
--hyprmod settings
hl.unbind("SUPER + SHIFT + Left")
hl.bind("SUPER + SHIFT + Left", hl.dsp.focus({ workspace = -1 }))
hl.unbind("SUPER + SHIFT + Right")
hl.bind("SUPER + SHIFT + Right", hl.dsp.focus({ workspace = "+1" }))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --output-folder ~/Pictures/Screenshots"))
hl.bind("SUPER + CTRL + Right", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPER + CTRL + Left", hl.dsp.window.move({ workspace = -1 }))
-- Env vars (Variance by graphics drivers)
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GL_GSYNC_ALLOWED", "0")
hl.env("__GL_VRR_ALLOWED", "0")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
-- Force Qt apps to use qt5ct/qt6ct for styling layouts
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- Ensure Qt apps pick up Wayland instead of fallback X11 layouts
hl.env("QT_QPA_PLATFORM", "wayland")

hl.config({
    layerrule = {
        "blur, quickshell-bar",
        "ignorealpha 0.4, quickshell-bar", -- lets blur render through semi-transparent areas; tune threshold to your CSS alpha
    }
})


-- Consolidated decoration/blur block (previously split across 3 hl.config calls
-- that overwrote each other; only the last one was ever actually in effect)
hl.config({
    decoration = {
        rounding = 8,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            xray = true,
        },
        shadow = {
            enabled = false,
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        accel_profile = "flat",
        sensitivity = 0.0,
    },
})
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 0,
        ["col.active_border"]   = "rgba(" .. colors.overlay1Alpha .. "ee)",    
        ["col.inactive_border"] = "rgba(" .. colors.surface1Alpha .. "99)",  
        resize_on_border = true,
        extend_border_grab_area = 20,  -- pixels of grab area beyond the visible border
        hover_icon_on_border = true,
    },
})
hl.config({
    cursor = {
        inactive_timeout = 0,
        no_hardware_cursors = true,
    },
})
-- anims here
-- Define curves first
hl.curve("sharp", { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("snappy", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1} } })
hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })

-- Then reference them by leaf
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "snappy", style = "popin 90%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.6, bezier = "sharp", style = "popin 90%" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "linear" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "sharp" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.2, bezier = "snappy", style = "slide" })
hl.animation({ leaf = "layers", enabled = true, speed = 1.6, bezier = "sharp" })
hl.bind("Caps_Lock", hl.dsp.exec_cmd("sleep 0.1 && ~/.config/hypr/scripts/capslock.sh"))

-- Try using the shorthand variant if the full word is being ignored

hl.bind("SUPER + J", hl.dsp.focus({ workspace = "-1" }))
hl.bind("SUPER + K", hl.dsp.focus({ workspace = "+1" }))

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))


-- Trigger the rofi power menu

hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))

hl.bind("SUPER + Q", hl.dsp.window.close())

hl.bind("SUPER + SHIFT + E", hl.dsp.exit())


-- Captures the entire screen and copies it directly to your clipboard
-- Pressing Print captures the entire screen straight to your clipboard


-- True fullscreen (Hides waybar and gaps)

hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + V", hl.dsp.window.float())

-- Forces every window on the workspace into floating mode

hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("hyprctl clients -j| jq -r '.[]| select(.workspace.id=='$(hyprctl activeworkspace -j| jq '.id')')| . address'| xargs -I { } hyprctl dispatch togglefloating address:{ }"))

-- Toggle Rofi App Launcher using Super and Tab

hl.bind("SUPER + TAB", hl.dsp.exec_cmd("pkill rofi || rofi -show drun -theme-str 'window { close-on-click:true; } '"))

-- Delete or replace the bottom section with ONLY this line:

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- TODO: manual review: blurls = "waybar"

-- Autostart
hl.on("hyprland.start", function()
   hl.exec_cmd("qs")
   hl.exec_cmd("awww-daemon")
   hl.exec_cmd("awww img ~/Pictures/Wallpapers/hk.png")
   hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
   hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
   hl.exec_cmd("eww daemon")
   hl.exec_cmd("playerctld daemon")
end)

-- HyprMod managed settings
--require("hyprland-gui")
-- hyprbars settings go inside hl.config under plugin
--[[hl.config({
    plugin = {
        hyprbars = {
            bar_height = 20,
            bar_color = colors.base,
            ["col.text"] = colors.text,
            bar_text_size = 14,
            bar_text_font = "SF Pro Text",
            bar_button_padding = 10,
            bar_padding = 10,
            bar_precedence_over_border = true,
            bar_part_of_window = true,
        }
    }
})

-- buttons are added separately
hl.plugin.hyprbars.add_button({
    bg_color = colors.red,
    fg_color = colors.base,
    size = 15,
    icon = "󱎘",
    action = "hyprctl dispatch 'hl.dsp.window.close()'",
})
hl.plugin.hyprbars.add_button({
    bg_color = colors.green,
    fg_color = colors.base,
    size = 15,
    icon = "",
    action = "hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = \"maximized\", action = \"toggle\" })'",
})
hl.plugin.hyprbars.add_button({
    bg_color = colors.mauve,
    fg_color = colors.base,
    size = 15,
    icon = "",
    action = "hyprctl dispatch 'hl.dsp.window.float({action=\"toggle\"})'",
})
]]
    '';
  };

  programs.rofi = {
    enable = true;
    settings = {
      modi = "drun,run,filebrowser";
      show-icons = true;
      display-drun = "";
      display-run = "";
      display-filebrowser = "";
      drun-display-format = "{name}";
    };
    theme = lib.mkForce (
      let
        inherit (config.lib.formats.rasi) mkLiteral;
      in
      {
        # Mocha palette file written to ~/.local/share/rofi/themes by catppuccin/nix
        "@import" = "catppuccin-mocha";
        "*" = {
          background = mkLiteral "@base";
          background-alt = mkLiteral "@surface0";
          foreground = mkLiteral "@text";
          selected = mkLiteral "@lavender";
          active = mkLiteral "@green";
          urgent = mkLiteral "@red";
          font = "JetBrainsMono Nerd Font 11";
        };
        "window" = {
          transparency = "real";
          location = mkLiteral "west";
          anchor = mkLiteral "west";
          fullscreen = false;
          width = mkLiteral "500px";
          height = mkLiteral "96%";
          x-offset = mkLiteral "20px";
          y-offset = mkLiteral "0px";
          enabled = true;
          margin = mkLiteral "0px";
          padding = mkLiteral "0px";
          border = mkLiteral "4px solid";
          border-color = mkLiteral "@background-alt";
          cursor = "default";
          background-color = mkLiteral "@background";
        };
        "mainbox" = {
          enabled = true;
          spacing = mkLiteral "20px";
          margin = mkLiteral "0px";
          padding = mkLiteral "20px";
          background-color = mkLiteral "transparent";
          children = [ "inputbar" "message" "listview" "mode-switcher" ];
        };
        "inputbar" = {
          enabled = true;
          spacing = mkLiteral "10px";
          margin = mkLiteral "0px";
          padding = mkLiteral "10px";
          background-color = mkLiteral "@background-alt";
          text-color = mkLiteral "@foreground";
          children = [ "textbox-prompt-colon" "entry" ];
        };
        "prompt" = {
          enabled = true;
          background-color = mkLiteral "inherit";
          text-color = mkLiteral "inherit";
        };
        "textbox-prompt-colon" = {
          enabled = true;
          padding = mkLiteral "0px";
          expand = false;
          str = " ";
          background-color = mkLiteral "inherit";
          text-color = mkLiteral "inherit";
        };
        "entry" = {
          enabled = true;
          padding = mkLiteral "0px";
          background-color = mkLiteral "inherit";
          text-color = mkLiteral "inherit";
          cursor = mkLiteral "text";
          placeholder = "Search...";
          placeholder-color = mkLiteral "inherit";
        };
        "listview" = {
          enabled = true;
          columns = 1;
          lines = 12;
          cycle = true;
          dynamic = true;
          scrollbar = true;
          layout = mkLiteral "vertical";
          reverse = false;
          fixed-height = true;
          fixed-columns = true;
          spacing = mkLiteral "5px";
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "@foreground";
          cursor = "default";
        };
        "scrollbar" = {
          handle-width = mkLiteral "5px";
          handle-color = mkLiteral "@selected";
          background-color = mkLiteral "@background-alt";
        };
        "element" = {
          enabled = true;
          spacing = mkLiteral "10px";
          margin = mkLiteral "0px";
          padding = mkLiteral "6px";
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "@foreground";
          cursor = mkLiteral "pointer";
        };
        "element normal.normal, element alternate.normal" = {
          background-color = mkLiteral "var(background)";
          text-color = mkLiteral "var(foreground)";
        };
        "element normal.urgent, element alternate.urgent, element selected.active" = {
          background-color = mkLiteral "var(urgent)";
          text-color = mkLiteral "var(background)";
        };
        "element normal.active, element alternate.active, element selected.urgent" = {
          background-color = mkLiteral "var(active)";
          text-color = mkLiteral "var(background)";
        };
        "element selected.normal" = {
          background-color = mkLiteral "var(selected)";
          text-color = mkLiteral "var(background)";
        };
        "element-icon" = {
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "inherit";
          size = mkLiteral "24px";
          cursor = mkLiteral "inherit";
        };
        "element-text" = {
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "inherit";
          highlight = mkLiteral "inherit";
          cursor = mkLiteral "inherit";
          vertical-align = mkLiteral "0.5";
          horizontal-align = mkLiteral "0.0";
        };
        "mode-switcher" = {
          enabled = true;
          spacing = mkLiteral "10px";
          margin = mkLiteral "0px";
          padding = mkLiteral "0px 0px";
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "@foreground";
        };
        "button" = {
          padding = mkLiteral "10px";
          background-color = mkLiteral "@background-alt";
          text-color = mkLiteral "inherit";
          cursor = mkLiteral "pointer";
        };
        "button selected" = {
          background-color = mkLiteral "var(urgent)";
          text-color = mkLiteral "var(background)";
        };
        "message" = {
          enabled = true;
          margin = mkLiteral "0px";
          padding = mkLiteral "10px";
          background-color = mkLiteral "@background-alt";
          text-color = mkLiteral "@foreground";
        };
        "textbox" = {
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "@foreground";
          vertical-align = mkLiteral "0.5";
          horizontal-align = mkLiteral "0.0";
          highlight = mkLiteral "none";
          placeholder-color = mkLiteral "@foreground";
          blink = true;
          markup = true;
        };
        "error-message" = {
          padding = mkLiteral "20px";
          background-color = mkLiteral "@background";
          text-color = mkLiteral "@foreground";
        };
      });
  };



  programs.fastfetch = {
    enable = true;
    settings = {
      "$schema" = "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json";
      logo = {
        padding = {
          top = 1;
          right = 3;
        };
      };
      display = {
        separator = " │ ";
      };
      modules = [
        {
          type = "custom";
          format = "╭───────────╮";
        }
        {
          type = "user";
          key = "│ user    ";
          keyColor = "red";
        }
        {
          type = "host";
          key = "│󰋜 hname   ";
          keyColor = "green";
        }
        {
          type = "command";
          key = "│󰋔 os age  ";
          keyColor = "yellow";
          text = "birth_install=$(stat -c %W /); current=$(date +%s); time_progression=$((current - birth_install)); days_difference=$((time_progression / 86400)); echo $days_difference days";
        }
        {
          type = "uptime";
          key = "│󱎫 uptime  ";
          keyColor = "blue";
        }
        {
          type = "os";
          key = "│ distro  ";
          keyColor = "cyan";
        }
        {
          type = "kernel";
          key = "│󰒋 kernel  ";
          keyColor = "magenta";
        }
        {
          type = "wm";
          key = "│󱂬 wm      ";
          keyColor = "green";
        }
        {
          type = "lm";
          key = "│󰧨 desktop ";
          keyColor = "cyan";
        }
        {
          type = "terminal";
          key = "│ term    ";
          keyColor = "red";
        }
        {
          type = "shell";
          key = "│󰞷 shell   ";
          keyColor = "green";
        }
        {
          type = "cpu";
          key = "│󰻠 cpu     ";
          keyColor = "yellow";
        }
        {
          type = "gpu";
          key = "│󰢮 gpu     ";
          keyColor = "yellow";
        }
        {
          type = "disk";
          key = "│󰋊 disk    ";
          keyColor = "blue";
        }
        {
          type = "memory";
          key = "│󰍛 memory  ";
          keyColor = "cyan";
        }
        {
          type = "localip";
          key = "│ local ip";
          keyColor = "blue";
        }
        {
          type = "packages";
          key = "│ packages";
          keyColor = "green";
        }
        {
          type = "custom";
          format = "├───────────┤";
        }
        {
          type = "colors";
          key = "│🎨 colors ";
          symbol = "circle";
        }
        {
          type = "custom";
          format = "╰───────────╯";
        }
      ];
    };
  };

  programs.kitty = {
    enable = true;
    themeFile = lib.mkForce null;
    font.name = "JetBrainsMono Nerd Font Mono";
    shellIntegration = {
      mode = null; # set via settings below, so HM does not force "no-rc"
      enableBashIntegration = false;
      enableZshIntegration = false;
      enableFishIntegration = false;
    };
    settings = {
      remember_window_size = "no";
      scrollback_lines = 10000;
      background_opacity = "0.7";
      cursor_shape = "beam";
      shell_integration = "no-cursor";
      cursor_trail = 1;
      repaint_delay = 5;
      input_delay = 1;
      sync_to_monitor = "no";
      confirm_os_window_close = 0;
      cursor_trail_start_threshold = 0;
      foreground = "#CDD6F4";
      background = "#1E1E2E";
      selection_foreground = "#1E1E2E";
      selection_background = "#F5E0DC";
      cursor = "#F5E0DC";
      cursor_text_color = "#1E1E2E";
      url_color = "#F5E0DC";
      active_border_color = "#B4BEFE";
      inactive_border_color = "#6C7086";
      bell_border_color = "#F9E2AF";
      wayland_titlebar_color = "system";
      active_tab_foreground = "#11111B";
      active_tab_background = "#CBA6F7";
      inactive_tab_foreground = "#CDD6F4";
      inactive_tab_background = "#181825";
      tab_bar_background = "#11111B";
      mark1_foreground = "#1E1E2E";
      mark1_background = "#B4BEFE";
      mark2_foreground = "#1E1E2E";
      mark2_background = "#CBA6F7";
      mark3_foreground = "#1E1E2E";
      mark3_background = "#74C7EC";
      color0 = "#45475A";
      color8 = "#585B70";
      color1 = "#F38BA8";
      color9 = "#F38BA8";
      color2 = "#A6E3A1";
      color10 = "#A6E3A1";
      color3 = "#F9E2AF";
      color11 = "#F9E2AF";
      color4 = "#89B4FA";
      color12 = "#89B4FA";
      color5 = "#F5C2E7";
      color13 = "#F5C2E7";
      color6 = "#94E2D5";
      color14 = "#94E2D5";
      color7 = "#BAC2DE";
      color15 = "#A6ADC8";
    };
  };
  # kitty rewrites kitty.conf itself (e.g. the font/theme kittens), turning HM's
  # symlink into a regular file; force lets HM replace it
  xdg.configFile."kitty/kitty.conf".force = true;

gtk = {
  enable = true;
  theme = {
    name = "catppuccin-mocha-blue-standard"; # whatever GTK theme you have installed
    package = pkgs.catppuccin-gtk.override {
      accents = [ "blue" ];
      size = "standard";
      variant = "mocha";
    };
  };
    gtk4.theme = config.gtk.theme;


  font = {
    name = "SFProText Nerd Font";
    size = 11;
  };

  gtk3.extraConfig = {
    gtk-application-prefer-dark-theme = true;
  };

  gtk4.extraConfig = {
    gtk-application-prefer-dark-theme = true;
  };
};


home.pointerCursor = {
  enable = true;
  gtk.enable = true;
  x11.enable = true;
  name = "catppuccin-mocha-mauve-cursors";
  package = pkgs.catppuccin-cursors.mochaMauve;
};

gtk.cursorTheme = {
  name = "catppuccin-mocha-mauve-cursors";
  package = pkgs.catppuccin-cursors.mochaMauve;
};

programs.bash = {
  enable = true;
  shellAliases = {
    ll = "lsd -la";
    ls = "lsd";
    gs = "git status";
    update = "cd /etc/nixos && sudo nix flake update && sudo nixos-rebuild switch --flake /etc/nixos#nixos && cd && flatpak update -y";
    viconfig = "sudo fresh /etc/nixos/configuration.nix";
    clean = "nh clean all";
    reload = "source ~/.bashrc";
  };
  bashrcExtra = ''
    source -- "${pkgs.blesh}/share/blesh/ble.sh" --noattach
    eval "$(starship init bash)"
    export PATH=~/bin:$PATH
    export PATH="$HOME/.npm-global/bin:$PATH"
    fastfetch
    [[ ! ''${BLE_VERSION-} ]] || ble-attach
  '';
};

  # Lock screen (launched from the waybar lock button)
  # Measured from the reference screenshot and scaled to 1920x1080
  programs.hyprlock = {
    enable = true;
    package = null; # hyprlock is installed system-wide in configuration.nix (needed for PAM)
    # no mkForce: catppuccin sources its Mocha palette ($rosewater, $surface0, ...);
    # its default layout is turned off with useDefaultConfig = false below
    settings = {
      general = {
        hide_cursor = false; # cursor is visible in the reference
      };

      background = [
        {
          monitor = "";
          path = "${config.home.homeDirectory}/Pictures/Wallpapers/hk.png";
          blur_passes = 3;
        }
      ];

      # Clock: 07:44 — ink ~238x64px, centered 74px above screen center
      label = [
        {
          monitor = "";
          text = "$TIME";
          color = "$rosewater";
          font_size = 64;
          font_family = "JetBrainsMono Nerd Font";
          position = "0, 74";
          halign = "center";
          valign = "center";
        }
      ];

      # Password pill: ~225x56px, centered 27px below screen center
      input-field = [
        {
          monitor = "";
          size = "200, 50";
          position = "0, -20";
          halign = "center";
          valign = "center";
          rounding = -1; # full pill
          outline_thickness = 3;
          outer_color = "$rosewater";
          inner_color = "$surface0";
          font_color = "$rosewater";
          font_family = "JetBrainsMono Nerd Font";
          placeholder_text = "<i>Input Password...</i>";
          fade_on_empty = false;
          dots_center = true;
          check_color = "$yellow";
          fail_color = "$red";
          dots_size = 0.33;    # 0.2–0.8, fraction of the field height
          dots_spacing = 0.15; # 0.0–1.0, gap between dots, relative to dot size
        }
      ];
    };
  };
  # keep catppuccin's palette for hyprlock, but not its corner clock / layout / mauve field
  catppuccin.hyprlock.useDefaultConfig = false;
  # replaces any hand-written ~/.config/hypr/hyprlock.conf instead of failing activation
  xdg.configFile."hypr/hyprlock.conf".force = true;
}
